- rust/operator-binary/src/druid_controller.rs
Clippy in Rust 1.58 introduced a new warning, this fixes it.
> Fix Rust 1.58 clippy warning

- CHANGELOG.md
- deploy/helm/druid-operator/crds/crds.yaml
- rust/crd/src/lib.rs
Add missing crd defaults (#439)
cherry picked from commit 2a1ed255ea4009f07d7892dfdf17041ddde612f6
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Add missing crd defaults to 23.4

- CHANGELOG.md
- tests/kuttl-test.yaml.jinja2
- tests/templates/kuttl/logging/01-install-druid-vector-aggregator.yaml
- tests/templates/kuttl/logging/druid-vector-aggregator-values.yaml.j2
- tests/templates/kuttl/logging/test_log_aggregation.py
Upgrade Vector
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Upgrade vector

- deploy/helm/druid-operator/crds/crds.yaml
- docs/modules/druid/pages/usage-guide/listenerclass.adoc
- docs/modules/druid/partials/nav.adoc
- rust/crd/src/lib.rs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> ListenerClass docs

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deploy/helm/druid-operator/crds/crds.yaml
- rust/crd/src/authentication/ldap.rs
- rust/crd/src/security.rs
- rust/operator-binary/src/druid_controller.rs
fixes https://github.com/stackabletech/druid-operator/issues/468
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Let secret operator create pkcs12 stores

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deploy/helm/druid-operator/crds/crds.yaml
- docs/modules/druid/examples/getting_started/druid.yaml
- docs/modules/druid/examples/getting_started/druid.yaml.j2
- docs/modules/druid/examples/getting_started/hdfs.yaml
- docs/modules/druid/examples/getting_started/hdfs.yaml.j2
- docs/modules/druid/examples/getting_started/zookeeper.yaml
- docs/modules/druid/examples/getting_started/zookeeper.yaml.j2
- docs/modules/druid/partials/supported-versions.adoc
- examples/psql-s3/psql-s3-druid-cluster.yaml
- examples/psql/psql-hdfs-druid-cluster.yaml
- examples/tls/tls-druid-cluster.yaml
- rust/crd/src/affinity.rs
- rust/crd/test/resources/resource_merge/druid_cluster.yaml
- rust/crd/test/resources/resource_merge/segment_cache.yaml
- rust/crd/test/resources/role_service/druid_cluster.yaml
- rust/operator-binary/src/druid_controller.rs
- rust/operator-binary/test/resources/druid_controller/segment_cache.yaml
- tests/templates/kuttl/logging/01-install-druid-vector-aggregator.yaml
- tests/test-definition.yaml
- added support for 27.0.0
- removed support for 0.23.0, 24.0.0
- bump vector aggregator
- bump other product versions in test / examples
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> New version 27.0.0

- docs/modules/druid/examples/getting_started/getting_started.sh
- docs/modules/druid/examples/getting_started/getting_started.sh.j2
- docs/modules/druid/pages/getting_started/installation.adoc
- docs/modules/druid/pages/index.adoc
- docs/templating_vars.yaml
The listener-operator is now one of the fundamental operators, along with the commons- and secret-operators, and should be mentioned accordingly everywhere.
```[tasklist]
```
```[tasklist]
```
> docs: Add listener-operator where missing

- .readme/README.md.j2
- Cargo.toml
- README.md
So far we would include files with all their whitespace which can lead to markdownlint errors and inconsistencies. Now we trim everything we include.
This also switches to resolver v2 for the workspace because the `render-readme` step would warn about it.
Part of https://github.com/stackabletech/issues/issues/492
>  Fix whitespace control in README generation

- CHANGELOG.md
- docs/modules/druid/examples/getting_started/druid.yaml
- docs/modules/druid/examples/getting_started/druid.yaml.j2
- docs/modules/druid/partials/supported-versions.adoc
- examples/psql-s3/psql-s3-druid-cluster.yaml
- examples/psql/psql-hdfs-druid-cluster.yaml
- examples/tls/tls-druid-cluster.yaml
- rust/crd/src/affinity.rs
- rust/crd/test/resources/resource_merge/druid_cluster.yaml
- rust/crd/test/resources/resource_merge/segment_cache.yaml
- rust/crd/test/resources/role_service/druid_cluster.yaml
- rust/operator-binary/test/resources/druid_controller/segment_cache.yaml
- tests/templates/kuttl/oidc/30-druid.yaml.j2
- tests/test-definition.yaml
fixes https://github.com/stackabletech/druid-operator/issues/503
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Support druid 28.0.1

- tests/release.yaml
- tests/templates/kuttl/authorizer/00-patch-ns.yaml.j2
- tests/templates/kuttl/cluster-operation/00-patch-ns.yaml.j2
- tests/templates/kuttl/hdfs-deep-storage/00-patch-ns.yaml.j2
- tests/templates/kuttl/ingestion-no-s3-ext/00-patch-ns.yaml.j2
- tests/templates/kuttl/ingestion-s3-ext/00-patch-ns.yaml.j2
- tests/templates/kuttl/ldap-authentication/00-patch-ns.yaml.j2
- tests/templates/kuttl/logging/00-patch-ns.yaml.j2
- tests/templates/kuttl/oidc/00-patch-ns.yaml.j2
- tests/templates/kuttl/orphaned-resources/00-patch-ns.yaml.j2
- tests/templates/kuttl/resources/00-patch-ns.yaml.j2
- tests/templates/kuttl/s3-deep-storage/00-patch-ns.yaml.j2
- tests/templates/kuttl/smoke/00-patch-ns.yaml.j2
- tests/templates/kuttl/tls/00-patch-ns.yaml.j2
- tests/test-definition.yaml
Part of stackabletech/issues#566.
OKD:
```
--- PASS: kuttl (5423.66s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/s3-deep-storage_druid-latest-28.0.1_zookeeper-latest-3.9.1_s3-use-tls-true_openshift-true (596.11s)
--- PASS: kuttl/harness/resources_druid-latest-28.0.1_zookeeper-latest-3.9.1_openshift-true (181.74s)
--- PASS: kuttl/harness/hdfs-deep-storage_druid-latest-28.0.1_zookeeper-latest-3.9.1_hadoop-3.3.6_openshift-true (474.69s)
--- PASS: kuttl/harness/tls_druid-latest-28.0.1_zookeeper-latest-3.9.1_tls-mode-internal-and-server-tls-and-tls-client-auth_openshift-true (379.50s)
--- PASS: kuttl/harness/oidc_druid-latest-28.0.1_zookeeper-latest-3.9.1_s3-use-tls-true_openshift-true (339.05s)
--- PASS: kuttl/harness/authorizer_druid-28.0.1_zookeeper-latest-3.9.1_opa-0.61.0_hadoo …
```
> tests: added namespace patch for openshift tests

- docs/modules/druid/pages/usage-guide/deep-storage.adoc
The documentation for deep storage has moved: https://druid.apache.org/docs/latest/design/deep-storage/
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Docs: Fix broken link to deep storage documentation

- CHANGELOG.md
- rust/crd/src/lib.rs
Leftover of #547.
As we now have access to https://github.com/kube-rs/kube/pull/1484, we can get rid of the workaround
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: Remove custom schema workaround for HashSet

- tests/templates/kuttl/oidc/login.py
The OIDC test fails with the following error:
```
2024-06-18 01:20:49,555 DEBUG: Starting new HTTPS connection (1): druid-router-default:9088
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 467, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 653, in connect
sock_and_verified = _ssl_wrap_socket_and_match_hostname(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
ssl_sock = ssl_wrap_socket(
^^^^^^^^^^^^^^^^
File …
```
> Fix the OIDC test

- tests/templates/kuttl/oidc/20-zookeeper.yaml
- tests/templates/kuttl/oidc/40_druid.yaml.j2
Fixing hardcoded
`stackableVersion: 23.7.0`
as it broke integration tests on ARM and is not supposed to be used anymore as we have `ImageSelection` by operator version.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Remove stackableVersion from ZookeeperCluster CRD

- rust/operator-binary/src/internal_secret.rs
Re-creating immutable secrets with the same name is error-prone, because of caching mechanisms internal to kubernetes (see https://github.com/kubernetes/website/issues/42359#issuecomment-2136192995). Deleting the immutable secret and re-creating it with a new name fixes this problem.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix: Re-create shared internal secret with a new name

- docs/modules/druid/pages/usage-guide/security.adoc
This currently breaks the build of our docs.
I tested the fix locally, works.
> Fix broken AuthenticationClass link in docs

- docs/modules/druid/examples/getting_started/getting_started.sh
- docs/modules/druid/examples/getting_started/getting_started.sh.j2
- docs/templating_vars.yaml
Left over from https://github.com/stackabletech/druid-operator/pull/589
Only doc template changes
> docs(getting-started): Make zookeeper templating variable consistent with other operators

- tests/templates/kuttl/authorizer/04-install-druid.yaml.j2
- tests/templates/kuttl/cluster-operation/30-install-druid.yaml.j2
- tests/templates/kuttl/hdfs-deep-storage/03-install-druid.yaml.j2
- tests/templates/kuttl/ingestion-no-s3-ext/03-install-druid.yaml.j2
- tests/templates/kuttl/ingestion-s3-ext/03-install-druid.yaml.j2
- tests/templates/kuttl/logging/05-install-druid.yaml.j2
- tests/templates/kuttl/orphaned-resources/03-install-druid.yaml.j2
- tests/templates/kuttl/resources/30-install-druid.yaml.j2
- tests/templates/kuttl/s3-deep-storage/10-install-druid.yaml.j2
- tests/templates/kuttl/smoke/50-assert.yaml
- tests/templates/kuttl/smoke/50-install-druid.yaml.j2
- tests/templates/kuttl/tls/04-install-druid.yaml.j2
This change allows to quickly delete namespaces after an integration test completed.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> test: Set all graceful shutdown timeouts in integrations tests to 1s

- tests/templates/kuttl/overrides/21-assert.yaml
- tests/templates/kuttl/overrides/22-assert.yaml
Kuttl hard codes `sh -c`, instead of allowing alternative shells to be used.
For now, we need to drop the `-o pipefail` option.
I think https://github.com/kudobuilder/kuttl/issues/50 was incorrectly closed, as the issue author asked for "bash script".
> [!NOTE]
> For Macos and NixOs users, `sh` appears to work like bash, so locally `set -euo pipfail` worked fine.
> test(kuttl): Remove the -o pipefail bash option

- docs/modules/druid/pages/getting_started/first_steps.adoc
- docs/modules/druid/pages/getting_started/index.adoc
- docs/modules/druid/pages/getting_started/installation.adoc
- docs/modules/druid/pages/index.adoc
- docs/modules/druid/pages/reference/commandline-parameters.adoc
- docs/modules/druid/pages/reference/crds.adoc
- docs/modules/druid/pages/reference/discovery.adoc
- docs/modules/druid/pages/reference/environment-variables.adoc
- docs/modules/druid/pages/required-external-components.adoc
- docs/modules/druid/pages/usage-guide/configuration-and-environment-overrides.adoc
- docs/modules/druid/pages/usage-guide/deep-storage.adoc
- docs/modules/druid/pages/usage-guide/extensions.adoc
- docs/modules/druid/pages/usage-guide/ingestion.adoc
- docs/modules/druid/pages/usage-guide/operations/cluster-operations.adoc
- docs/modules/druid/pages/usage-guide/operations/graceful-shutdown.adoc
- docs/modules/druid/pages/usage-guide/operations/pod-disruptions.adoc
- docs/modules/druid/pages/usage-guide/operations/pod-placement.adoc
- docs/modules/druid/pages/usage-guide/resources-and-storage.adoc
- docs/modules/druid/pages/usage-guide/security.adoc
- docs/modules/druid/partials/s3-credentials.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: pod overrides and other improvements

- CHANGELOG.md
- docs/modules/druid/examples/getting_started/druid.yaml
- docs/modules/druid/examples/getting_started/druid.yaml.j2
- docs/modules/druid/partials/supported-versions.adoc
- examples/psql-s3/psql-s3-druid-cluster.yaml
- examples/psql/psql-hdfs-druid-cluster.yaml
- examples/tls/tls-druid-cluster.yaml
- rust/crd/src/affinity.rs
- rust/crd/test/resources/resource_merge/druid_cluster.yaml
- rust/crd/test/resources/resource_merge/segment_cache.yaml
- rust/crd/test/resources/role_service/druid_cluster.yaml
- rust/operator-binary/test/resources/druid_controller/segment_cache.yaml
- rust/operator-binary/test/resources/druid_controller/simple.yaml
- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/833
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: promote Druid 30.0.0 to LTS, deprecate 26.0.0, remove 28.0.1

- CHANGELOG.md
- rust/operator-binary/src/druid_controller.rs
- rust/operator-binary/src/main.rs
Part if: https://github.com/stackabletech/issues/issues/211
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix: don't stop reconciliation if one cluster is invalid

- docs/modules/druid/examples/getting_started/getting_started.sh
- docs/modules/druid/examples/getting_started/getting_started.sh.j2
Part of https://github.com/stackabletech/issues/issues/657.
Uses `--server-side` for deploying druid resource so that `null` fields are honoured.
> [!NOTE]
> During a Stackable release we need to check (and optionally update) the
> getting-started scripts to ensure they still work after product and operator
> updates.
```shell
pushd $(fd -td getting_started | grep examples); cd code 2>/dev/null || true
kind delete cluster && kind create cluster
./getting_started.sh stackablectl
kind delete cluster && kind create cluster
./getting_started.sh helm
popd
```
> fix(docs): Update getting-started script pre-24.11

- docs/modules/druid/pages/reference/environment-variables.adoc
Adds missing KUBERNETES_CLUSTER_DOMAIN environment variable to docs
part of https://github.com/stackabletech/issues/issues/668
> Adds missing KUBERNETES_CLUSTER_DOMAIN environment variable to docs

- docs/modules/druid/examples/getting_started/getting_started.sh
- docs/modules/druid/examples/getting_started/install_output.txt
Part of https://github.com/stackabletech/issues/issues/647.
> docs: Update release in getting_started

- CHANGELOG.md
- rust/crd/src/lib.rs
- rust/operator-binary/src/druid_controller.rs
- rust/operator-binary/src/product_logging.rs
- tests/templates/kuttl/smoke/50-assert.yaml
Part of: <https://github.com/stackabletech/issues/issues/527>
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> feat: run containerdebug in the background

- docs/modules/druid/examples/getting_started/druid.yaml
- docs/modules/druid/examples/getting_started/druid.yaml.j2
- docs/modules/druid/examples/getting_started/getting_started.sh
- docs/modules/druid/examples/getting_started/getting_started.sh.j2
- docs/modules/druid/examples/getting_started/hdfs.yaml
- docs/modules/druid/examples/getting_started/hdfs.yaml.j2
- docs/modules/druid/pages/getting_started/first_steps.adoc
1. We should never encourage derby! After reboot of the coordinator (24h at max), your Druid will loose all data.
2. Let's not disable TLS
```
[...]
Awaiting Druid rollout finish
Waiting for 1 pods to be ready...
partitioned roll out complete: 1 new pods have been updated...
partitioned roll out complete: 1 new pods have been updated...
partitioned roll out complete: 1 new pods have been updated...
partitioned roll out complete: 1 new pods have been updated...
partitioned roll out complete: 1 new pods have been updated...
Starting port-forwarding of port 9088
Submitting job
Task still running...
Task still running...
Task still running...
Task still running...
Task finished successfully!
Segments still loading...
Segments still loading...
Segments still loading...
Segments still …
```
> docs: Fix getting started guide to use Postgres and TLS

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- deploy/helm/druid-operator/crds/crds.yaml
- deploy/helm/druid-operator/values.yaml
- docs/modules/druid/pages/reference/environment-variables.adoc
- tests/templates/kuttl/authorizer/05-checks-container.yaml
- tests/templates/kuttl/hdfs-deep-storage/04-checks-container.yaml
- tests/templates/kuttl/ingestion-no-s3-ext/04-checks-container.yaml
- tests/templates/kuttl/ingestion-s3-ext/04-checks-container.yaml
- tests/templates/kuttl/ldap/03-install-test-druid.yaml
- tests/templates/kuttl/logging/06-install-druid-test-runner.yaml
- tests/templates/kuttl/oidc/51-install-test-container.yaml.j2
- tests/templates/kuttl/s3-deep-storage/07-checks-container.yaml
- tests/templates/kuttl/smoke/60-checks-container.yaml
- tests/templates/kuttl/tls/05-install-checks.yaml.j2
- tests/test-definition.yaml
Openshift tests:
```
--- PASS: kuttl (2476.76s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/resources_druid-latest-30.0.0_zookeeper-latest-3.9.2_openshift-true (197.09s)
--- PASS: kuttl/harness/ingestion-s3-ext_druid-latest-30.0.0_zookeeper-latest-3.9.2_hadoop-3.4.0_openshift-true (347.14s)
--- PASS: kuttl/harness/cluster-operation_druid-latest-30.0.0_zookeeper-latest-3.9.2_hadoop-latest-3.4.0_openshift-true (406.80s)
--- PASS: kuttl/harness/s3-deep-storage_druid-latest-30.0.0_zookeeper-latest-3.9.2_s3-use-tls-true_openshift-true (288.17s)
--- PASS: kuttl/harness/overrides_druid-latest-30.0.0_zookeeper-latest-3.9.2_hadoop-latest-3.4.0_openshift-true (212.21s)
--- PASS: kuttl/harness/smoke_druid-30.0.0_zookeeper-3.9.2_hadoop-3.4.0_openshift-true (297.51s)
--- PASS: …
```
> chore: add oci references, merge templating changes

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- docs/modules/druid/partials/s3-note.adoc
- rust/operator-binary/src/crd/mod.rs
- rust/operator-binary/src/druid_controller.rs
Replaces https://github.com/stackabletech/druid-operator/pull/696
Follow-up of https://github.com/stackabletech/druid-operator/pull/695
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> feat: Warn when a non-default region is configured

- docs/modules/druid/examples/getting_started/getting_started.sh
- docs/modules/druid/examples/getting_started/getting_started.sh.j2
- docs/templating_vars.yaml
Part of <https://github.com/stackabletech/issues/issues/697>
This PR bumps the `postgresql` chart to 16.5.0
```shell
kind delete cluster && kind create cluster
./getting_started.sh stackablectl
kind delete cluster && kind create cluster
./getting_started.sh helm
```
> chore(docs): Update getting-started script pre-25.3.0

- docs/modules/druid/examples/getting_started/getting_started.sh
- docs/modules/druid/examples/getting_started/getting_started.sh.j2
- docs/modules/druid/pages/getting_started/installation.adoc
- docs/templating_vars.yaml
Part of https://github.com/stackabletech/infrastructure/issues/142
Updating the helm install commands in Getting started sections of the operators was missed during Harbor migration of the docs.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: Update helm install commands

- CHANGELOG.md
- tests/templates/kuttl/authorizer/02-install-opa.yaml.j2
- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1084.
> test: Bump OPA to 1.4.2

- CHANGELOG.md
- rust/operator-binary/src/druid_controller.rs
Part of https://github.com/stackabletech/issues/issues/651
Remove hardcoded uid and gid, they'll default to the ones from the docker images now.
For 25.7 that means they might change from 1000/0
See https://github.com/stackabletech/docker-images/pull/916 for details
> chore: Remove hardcoded uid and gid

- CHANGELOG.md
- docs/modules/druid/examples/getting_started/druid.yaml
- docs/modules/druid/examples/getting_started/druid.yaml.j2
- docs/modules/druid/partials/supported-versions.adoc
- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1075.
- Add: `33.0.0`
- Deprecate: `31.0.1`
- Remove: `30.0.0`
> chore: Add support for 33.0.0, remove support for 30.0.0, deprecate 31.0.1

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- deploy/helm/druid-operator/crds/crds.yaml
- rust/operator-binary/src/authentication/ldap.rs
- rust/operator-binary/src/authentication/mod.rs
- rust/operator-binary/src/authentication/oidc.rs
- rust/operator-binary/src/crd/authentication.rs
- rust/operator-binary/src/crd/mod.rs
- rust/operator-binary/src/druid_controller.rs
- rust/operator-binary/src/extensions.rs
Bump stackable-operator to 0.93.0 which versions common CRD structs.
The CRD descriptions will be improved once changes like stackabletech/operator-rs#1040 are released.
> chore: Bump stackable_operator to 0.93.0

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- deploy/helm/druid-operator/crds/crds.yaml
- deploy/helm/druid-operator/templates/roles.yaml
- rust/operator-binary/src/crd/mod.rs
- rust/operator-binary/src/crd/security.rs
- rust/operator-binary/src/listener.rs
- rust/operator-binary/src/main.rs
Part of <https://github.com/stackabletech/issues/issues/725>
> [!NOTE]
> During a Stackable release we need to update various Rust dependencies before
> entering the final release period to ensure we run the latest versions of
> crates. These bumps also include previously updated and released crates from
> the `operator-rs` repository.
> [!NOTE]
> The bumping / updating of Rust dependencies is done in multiple steps:
>
> 1. Update the minimum Version in the root `Cargo.toml` manifest.
> 2. Run the `cargo update` command, which also updates the `Cargo.lock` file.
> 3. Lastly, run `make regenerate-nix` to update the `Cargo.nix` file.
> chore: Bump Rust dependencies pre-25.7.0

- CHANGELOG.md
- deploy/helm/druid-operator/templates/roles.yaml
Needed since https://github.com/stackabletech/operator-rs/pull/938
Not 100% sure why the product needs this, but it was this way before.
> fix: Add RBAC permission to patch events

- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- rust/operator-binary/src/crd/mod.rs
- rust/operator-binary/src/crd/security.rs
- rust/operator-binary/src/discovery.rs
- rust/operator-binary/src/druid_controller.rs
- rust/operator-binary/src/main.rs
- rust/operator-binary/src/operations/graceful_shutdown.rs
Part of https://github.com/stackabletech/issues/issues/762
> chore: Update to stackable-operator 0.95.0

- CHANGELOG.md
- docs/modules/druid/examples/getting_started/druid.yaml
- docs/modules/druid/examples/getting_started/druid.yaml.j2
- docs/modules/druid/partials/supported-versions.adoc
- tests/templates/kuttl/overrides/20-install-druid.yaml.j2
- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1234
Integrationtests mentioned here: https://github.com/stackabletech/docker-images/pull/1263
> chore: Bump druid version for 25.11.0

- CHANGELOG.md
- rust/operator-binary/src/authentication/ldap.rs
- rust/operator-binary/src/authentication/oidc.rs
- rust/operator-binary/src/crd/mod.rs
- rust/operator-binary/src/crd/security.rs
- tests/templates/kuttl/ldap/20-assert.yaml
While checking this I noticed TLS handling in druid-operator looks buggy to me.
Given it's Druid I did not further investigate, but restored the previous behavior of `keytool`.
The test should now pass again.
> fix: Auto-create truststore on certificate addition

- docs/modules/druid/examples/getting_started/hdfs.yaml
- docs/modules/druid/examples/getting_started/hdfs.yaml.j2
- examples/psql/psql-hdfs-druid-cluster.yaml
- examples/tls/tls-druid-cluster.yaml
- tests/test-definition.yaml
Bump hadoop to 3.4.2 and run affected tests:
```
--- PASS: kuttl (1983.64s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/external-access_druid-34.0.0_zookeeper-latest-3.9.3_opa-1.4.2_hadoop-3.4.2_openshift-false (501.61s)
--- PASS: kuttl/harness/authorizer_druid-34.0.0_zookeeper-latest-3.9.3_opa-1.4.2_hadoop-3.4.2_openshift-false (598.94s)
--- PASS: kuttl/harness/ingestion-s3-ext_druid-latest-34.0.0_zookeeper-latest-3.9.3_hadoop-3.4.2_openshift-false (332.25s)
--- PASS: kuttl/harness/logging_druid-34.0.0_zookeeper-latest-3.9.3_hadoop-3.4.2_openshift-false (323.60s)
--- PASS: kuttl/harness/ldap_druid-34.0.0_zookeeper-latest-3.9.3_opa-1.4.2_hadoop-latest-3.4.2_ldap-use-tls-true_ldap-no-bind-credentials-false_openshift-false (302.72s)
--- PASS: …
```
> chore: Bump hadoop to 3.4.2 prior to 25.11

- docs/modules/druid/examples/getting_started/zookeeper.yaml
- docs/modules/druid/examples/getting_started/zookeeper.yaml.j2
- examples/psql-s3/psql-s3-druid-cluster.yaml
- examples/psql/psql-hdfs-druid-cluster.yaml
- examples/tls/tls-druid-cluster.yaml
- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1275
```
--- FAIL: kuttl (7901.80s)
--- FAIL: kuttl/harness (0.00s)
--- PASS: kuttl/harness/ldap_druid-33.0.0_zookeeper-latest-3.9.4_opa-1.4.2_hadoop-latest-3.4.2_ldap-use-tls-false_ldap-no-bind-credentials-false_openshift-false (401.25s)
--- PASS: kuttl/harness/oidc_druid-30.0.1_zookeeper-latest-3.9.4_s3-use-tls-false_openshift-false_oidc-use-tls-false (506.42s)
--- PASS: kuttl/harness/resources_druid-latest-34.0.0_zookeeper-latest-3.9.4_openshift-false (189.29s)
--- PASS: kuttl/harness/orphaned-resources_druid-latest-34.0.0_zookeeper-latest-3.9.4_hadoop-3.4.2_openshift-false (475.79s)
--- PASS: kuttl/harness/cluster-operation_druid-latest-34.0.0_zookeeper-latest-3.9.4_hadoop-latest-3.4.2_openshift-false (485.30s)
--- PASS: …
```
> chore: Bump zookeeper version for 25.11.0

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- deploy/helm/druid-operator/crds/crds.yaml
- rust/operator-binary/src/main.rs
This reverts commit ed575ce0734a95606af7c46ae248fdfbe543db70.
This reverts commit ed575ce0734a95606af7c46ae248fdfbe543db70. (PR https://github.com/stackabletech/druid-operator/pull/759)
With https://github.com/stackabletech/druid-operator/pull/759 the kube-rs version was transitively bumped, which led to bugs in the CRD generation. @sbernauer will work on an upstream fix, then this revert can be reverted again later.
> Revert "feat: Add EoS checker (#759)"
