- examples/simple-druid-cluster-derby.yaml
> fixed example

- CHANGELOG.md
- Cargo.lock
- deploy/helm/druid-operator/Chart.yaml
- deploy/manifests/configmap.yaml
- deploy/manifests/deployment.yaml
- deploy/manifests/serviceaccount.yaml
- rust/crd/Cargo.toml
- rust/operator-binary/Cargo.toml
- rust/operator/Cargo.toml
Release 0.1.0. DO NOT SQUASH MERGE!
> Release 0.1.0

- docs/modules/ROOT/pages/usage.adoc
- examples/derby/druidcluster.yaml
- examples/psql-s3/druidcluster.yaml
- examples/psql/druidcluster.yaml
> Added empty object to config entry

- CHANGELOG.md
- Cargo.lock
- deploy/helm/druid-operator/Chart.yaml
- deploy/manifests/configmap.yaml
- deploy/manifests/deployment.yaml
- deploy/manifests/serviceaccount.yaml
- rust/crd/Cargo.toml
- rust/operator-binary/Cargo.toml
> Release 20211223123824

- Cargo.lock
- rust/crd/Cargo.toml
> Drop duplicate dependency

- CHANGELOG.md
- Cargo.lock
- README.md
- rust/crd/Cargo.toml
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/druid_controller.rs
- rust/operator-binary/src/main.rs
- README update
- Dependency updates
- Remove unused dependencies
- Graceful shutdown
- Rustdoc fixes
- 
> Various changes

- renovate.json
> Enable Renovate lock file maintenance

- docs/modules/druid/pages/usage.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fixed incorrect syntax

- Cargo.lock
- Cargo.toml
- deploy/helm/druid-operator/crds/crds.yaml
- rust/crd/Cargo.toml
- rust/operator-binary/Cargo.toml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Switch to workspace dependencies

- docs/modules/druid/pages/getting_started/first_steps.adoc
- docs/modules/druid/pages/index.adoc
- docs/modules/druid/pages/required-external-components.adoc
- docs/modules/druid/pages/usage-guide/deep-storage.adoc
- docs/modules/druid/partials/nav.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Added required external components

- docs/modules/druid/pages/getting_started/installation.adoc
- docs/modules/druid/pages/index.adoc
Part of https://github.com/stackabletech/stackable-cockpit/pull/101
> docs: Update references

- rust/operator-binary/src/druid_controller.rs
Part of https://github.com/stackabletech/operator-rs/issues/649
> refactor: Use operator-rs Duration

- Cargo.lock
- Cargo.toml
- rust/crd/Cargo.toml
- rust/crd/src/lib.rs
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/druid_controller.rs
Part of https://github.com/stackabletech/product-config/issues/95
> refactor: Use updated product-config

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deploy/helm/druid-operator/crds/crds.yaml
- rust/crd/src/authentication/mod.rs
- rust/crd/src/authorization.rs
- rust/crd/src/lib.rs
- rust/crd/src/storage.rs
- rust/operator-binary/src/main.rs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> More CRD docs!

- Cargo.lock
- Cargo.toml
- deploy/helm/druid-operator/crds/crds.yaml
- docs/modules/druid/partials/nav.adoc
- rust/crd/src/affinity.rs
- rust/crd/src/authentication/ldap.rs
- rust/crd/src/authentication/mod.rs
- rust/crd/src/lib.rs
- rust/crd/src/security.rs
- rust/operator-binary/src/discovery.rs
- rust/operator-binary/src/druid_controller.rs
see title
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: update operator-rs to 0.60

- CHANGELOG.md
- deploy/helm/druid-operator/templates/_helpers.tpl
- deploy/helm/druid-operator/templates/deployment.yaml
- deploy/helm/druid-operator/templates/roles.yaml
- deploy/helm/druid-operator/values.yaml
Part of: https://github.com/stackabletech/issues/issues/501
> feat(helm): support labels in values.yaml

- deploy/helm/druid-operator/values.yaml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Add Stackable vendor label to default values.yaml

- docs/modules/druid/pages/index.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: update index page: enhance supported version text and other minor changes

- docs/modules/druid/pages/usage-guide/logging.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: fix links but removing unnecessary 'home' part of the xref

- tests/templates/kuttl/oidc/00-druid-secrets.j2
- tests/templates/kuttl/oidc/00-s3-secret.yaml.j2
- tests/templates/kuttl/oidc/20-zookeeper.yaml.j2
- tests/templates/kuttl/oidc/40_druid.yaml.j2
- tests/templates/kuttl/resources/00-s3-secret.yaml.j2
- tests/templates/kuttl/s3-deep-storage/00-s3-secret.yaml.j2
- tests/templates/kuttl/tls/00-s3-secret.yaml.j2
- tests/test-definition.yaml
Fix some errors in the tests
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Fix some errors in the tests

- tests/templates/kuttl/logging/01-install-druid-vector-aggregator.yaml
Use Vector Helm chart version 0.34.0 (Vector 0.39.0) in the logging test
https://github.com/vectordotdev/helm-charts/blob/vector-0.34.0/CHANGELOG.md#vector-0340---2024-06-17
Implements stackabletech/docker-images#561
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Use Vector Helm chart version 0.34.0 in the logging test

- docs/modules/druid/examples/getting_started/zookeeper.yaml
- docs/modules/druid/examples/getting_started/zookeeper.yaml.j2
- examples/psql-s3/psql-s3-druid-cluster.yaml
- examples/psql/psql-hdfs-druid-cluster.yaml
- examples/tls/tls-druid-cluster.yaml
Sibling PR to https://github.com/stackabletech/druid-operator/pull/602
> chore: Use LTS ZooKeeper

- tests/templates/kuttl/logging/01-install-druid-vector-aggregator.yaml
Part of https://github.com/stackabletech/issues/issues/626
```[tasklist]
```
> chore: Bump Vector to 0.40.0

- deploy/helm/druid-operator/templates/roles.yaml
See: https://github.com/stackabletech/issues/issues/624
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> fix(helm): use same scc as olm

- tests/templates/kuttl/overrides/21-assert.yaml
- tests/templates/kuttl/overrides/22-assert.yaml
As [@NickLarsenNZ](https://github.com/NickLarsenNZ) pointed out we could get better in code style and readability. This are suggested changes of him first used in [stackabletech/superset-operator#533](https://github.com/stackabletech/superset-operator/pull/533) and now being propagated through operators.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Adapting according to new readability and code style

- CHANGELOG.md
- tests/test-definition.yaml
Part of stackabletech/docker-images#832.
```[tasklist]
```
> chore: Remove ZooKeeper to 3.8.4 from tests

- examples/psql/psql-hdfs-druid-cluster.yaml
- examples/tls/tls-druid-cluster.yaml
- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/835
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: bump hdfs version for tests and examples

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deploy/helm/druid-operator/crds/crds.yaml
- rust/crd/src/lib.rs
- rust/crd/src/resource.rs
- rust/crd/src/security.rs
- rust/operator-binary/src/authentication/mod.rs
- rust/operator-binary/src/druid_controller.rs
- rust/operator-binary/src/extensions.rs
- rust/operator-binary/src/internal_secret.rs
Part of https://github.com/stackabletech/issues/issues/640
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: Update to operator-rs 0.77.1 and use new S3 structs

- tests/templates/kuttl/overrides/20-install-druid.yaml.j2
Fix custom image usage in overrides test
> Fix custom image usage in overrides test

- docs/modules/druid/examples/getting_started/getting_started.sh
- docs/modules/druid/examples/getting_started/getting_started.sh.j2
Part of https://github.com/stackabletech/issues/issues/611.
Depends on https://github.com/stackabletech/druid-operator/pull/652.
> chore(getting_started): Replace templating instructions with make

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- deploy/helm/druid-operator/Chart.yaml
- docs/modules/druid/examples/getting_started/getting_started.sh
- docs/modules/druid/examples/getting_started/install_output.txt
- docs/templating_vars.yaml
- tests/release.yaml
> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.
> release: 24.11.1-rc2

- Cargo.lock
- Cargo.nix
Bump dependency versions
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: bump dependency versions

- .github/workflows/build.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- deploy/helm/druid-operator/Chart.yaml
- docs/modules/druid/examples/getting_started/getting_started.sh
- docs/modules/druid/examples/getting_started/install_output.txt
- docs/templating_vars.yaml
- tests/release.yaml
> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.
> release: 24.11.1

- tests/templates/kuttl/logging/01-install-druid-vector-aggregator.yaml
part of https://github.com/stackabletech/docker-images/issues/967
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: Update Vector to 0.43.1 in integration tests

- tests/templates/kuttl/authorizer/02-install-opa.yaml.j2
- tests/test-definition.yaml
Part of: https://github.com/stackabletech/docker-images/issues/969
Successful test run: https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/druid-operator-it-custom/28/
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: bump OPA to 1.0.0

- docs/modules/druid/examples/getting_started/zookeeper.yaml
- docs/modules/druid/examples/getting_started/zookeeper.yaml.j2
- examples/psql-s3/psql-s3-druid-cluster.yaml
- examples/psql/psql-hdfs-druid-cluster.yaml
- examples/tls/tls-druid-cluster.yaml
- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1020
> chore: Update ZooKeeper to 3.9.3 pre-25.3.0

- docs/modules/druid/examples/getting_started/hdfs.yaml
- docs/modules/druid/examples/getting_started/hdfs.yaml.j2
- examples/psql/psql-hdfs-druid-cluster.yaml
- examples/tls/tls-druid-cluster.yaml
- tests/test-definition.yaml
part of https://github.com/stackabletech/docker-images/issues/1018
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: Update HDFS to 3.4.1

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- deploy/helm/druid-operator/Chart.yaml
- deploy/helm/druid-operator/crds/crds.yaml
- docs/antora.yml
- docs/modules/druid/examples/getting_started/getting_started.sh
- docs/modules/druid/examples/getting_started/install_output.txt
- docs/templating_vars.yaml
- tests/release.yaml
> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.
> chore: Release 25.3.0

- tests/templates/kuttl/logging/01-install-druid-vector-aggregator.yaml
Part of: https://github.com/stackabletech/docker-images/issues/1146
> chore: bump vector chart to 0.43.0

- tests/templates/kuttl/resources/30-assert.yaml.j2
- tests/templates/kuttl/smoke/50-assert.yaml
Fix tests since #731 was implemented
> test: Update secret scopes in assertions

- CHANGELOG.md
- deploy/config-spec/properties.yaml
- deploy/helm/druid-operator/configs/properties.yaml
- rust/operator-binary/test/resources/druid_controller/properties.yaml
> fix: Backport Lot of configs missing for middleManagers

- tests/templates/kuttl/logging/01-install-druid-vector-aggregator.yaml
Part of https://github.com/stackabletech/docker-images/issues/1233
```
--- PASS: kuttl (747.73s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/logging_druid-33.0.0_zookeeper-latest-3.9.3_hadoop-3.4.1_openshift-false (378.80s)
--- PASS: kuttl/harness/logging_druid-30.0.1_zookeeper-latest-3.9.3_hadoop-3.4.1_openshift-false (482.27s)
--- PASS: kuttl/harness/logging_druid-31.0.1_zookeeper-latest-3.9.3_hadoop-3.4.1_openshift-false (368.89s)
PASS
```
> chore: Bump vector version for 25.11.0
